name: Sync Repo A → Repo B

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # If you build, do it here (e.g. npm ci && npm run build)
      - name: Prepare payload
        run: |
          rm -rf /tmp/payload && mkdir -p /tmp/payload
          rsync -a --delete --exclude ".git" ./ /tmp/payload/
          # If building, mirror only build output instead, e.g.:
          # rsync -a --delete ./dist/ /tmp/payload/

      - name: Push to Repo B main
        env:
          TOKEN: ${{ secrets.REPO_B_TOKEN }}
          OWNER: ${{ secrets.REPO_B_OWNER }}
          REPO:  ${{ secrets.REPO_B_NAME }}
        run: |
          set -euo pipefail
          cd /tmp/payload
          git init
          git config user.name  "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "Sync from $GITHUB_REPOSITORY@$GITHUB_SHA"
          git push --force "https://${OWNER}:${TOKEN}@github.com/${OWNER}/${REPO}.git" HEAD:main
